// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/AionApi/internal/admin/core/ports/output/admin_output.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/AionApi/internal/admin/core/ports/output/admin_output.go -destination=/home/lechitz/Projetos/AionApi/tests/mocks/admin_output_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
