// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/AionApi/internal/chat/core/ports/output/aion_chat_client.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/AionApi/internal/chat/core/ports/output/aion_chat_client.go -destination=/home/lechitz/Projetos/github/AionApi/tests/mocks/aion_chat_client_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/lechitz/AionApi/internal/chat/adapter/primary/http/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockAionChatClient is a mock of AionChatClient interface.
type MockAionChatClient struct {
	ctrl     *gomock.Controller
	recorder *MockAionChatClientMockRecorder
	isgomock struct{}
}

// MockAionChatClientMockRecorder is the mock recorder for MockAionChatClient.
type MockAionChatClientMockRecorder struct {
	mock *MockAionChatClient
}

// NewMockAionChatClient creates a new mock instance.
func NewMockAionChatClient(ctrl *gomock.Controller) *MockAionChatClient {
	mock := &MockAionChatClient{ctrl: ctrl}
	mock.recorder = &MockAionChatClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAionChatClient) EXPECT() *MockAionChatClientMockRecorder {
	return m.recorder
}

// SendMessage mocks base method.
func (m *MockAionChatClient) SendMessage(ctx context.Context, req *dto.InternalChatRequest) (*dto.InternalChatResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, req)
	ret0, _ := ret[0].(*dto.InternalChatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockAionChatClientMockRecorder) SendMessage(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockAionChatClient)(nil).SendMessage), ctx, req)
}
