// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/audit/core/ports/output/audit_action_event_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/audit/core/ports/output/audit_action_event_repository.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/audit_action_event_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lechitz/aion-api/internal/audit/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditActionEventRepository is a mock of AuditActionEventRepository interface.
type MockAuditActionEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditActionEventRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditActionEventRepositoryMockRecorder is the mock recorder for MockAuditActionEventRepository.
type MockAuditActionEventRepositoryMockRecorder struct {
	mock *MockAuditActionEventRepository
}

// NewMockAuditActionEventRepository creates a new mock instance.
func NewMockAuditActionEventRepository(ctrl *gomock.Controller) *MockAuditActionEventRepository {
	mock := &MockAuditActionEventRepository{ctrl: ctrl}
	mock.recorder = &MockAuditActionEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditActionEventRepository) EXPECT() *MockAuditActionEventRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAuditActionEventRepository) List(ctx context.Context, filter domain.AuditActionEventFilter) ([]domain.AuditActionEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter)
	ret0, _ := ret[0].([]domain.AuditActionEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAuditActionEventRepositoryMockRecorder) List(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditActionEventRepository)(nil).List), ctx, filter)
}

// Save mocks base method.
func (m *MockAuditActionEventRepository) Save(ctx context.Context, event domain.AuditActionEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAuditActionEventRepositoryMockRecorder) Save(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAuditActionEventRepository)(nil).Save), ctx, event)
}
