// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/category/core/ports/output/category_cache.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/category/core/ports/output/category_cache.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/category_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/aion-api/internal/category/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryCache is a mock of CategoryCache interface.
type MockCategoryCache struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryCacheMockRecorder
	isgomock struct{}
}

// MockCategoryCacheMockRecorder is the mock recorder for MockCategoryCache.
type MockCategoryCacheMockRecorder struct {
	mock *MockCategoryCache
}

// NewMockCategoryCache creates a new mock instance.
func NewMockCategoryCache(ctrl *gomock.Controller) *MockCategoryCache {
	mock := &MockCategoryCache{ctrl: ctrl}
	mock.recorder = &MockCategoryCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryCache) EXPECT() *MockCategoryCacheMockRecorder {
	return m.recorder
}

// DeleteCategory mocks base method.
func (m *MockCategoryCache) DeleteCategory(ctx context.Context, categoryID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoryCacheMockRecorder) DeleteCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategoryCache)(nil).DeleteCategory), ctx, categoryID, userID)
}

// DeleteCategoryByName mocks base method.
func (m *MockCategoryCache) DeleteCategoryByName(ctx context.Context, categoryName string, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryByName", ctx, categoryName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategoryByName indicates an expected call of DeleteCategoryByName.
func (mr *MockCategoryCacheMockRecorder) DeleteCategoryByName(ctx, categoryName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryByName", reflect.TypeOf((*MockCategoryCache)(nil).DeleteCategoryByName), ctx, categoryName, userID)
}

// DeleteCategoryList mocks base method.
func (m *MockCategoryCache) DeleteCategoryList(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryList", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategoryList indicates an expected call of DeleteCategoryList.
func (mr *MockCategoryCacheMockRecorder) DeleteCategoryList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryList", reflect.TypeOf((*MockCategoryCache)(nil).DeleteCategoryList), ctx, userID)
}

// GetCategory mocks base method.
func (m *MockCategoryCache) GetCategory(ctx context.Context, categoryID, userID uint64) (domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].(domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockCategoryCacheMockRecorder) GetCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockCategoryCache)(nil).GetCategory), ctx, categoryID, userID)
}

// GetCategoryByName mocks base method.
func (m *MockCategoryCache) GetCategoryByName(ctx context.Context, categoryName string, userID uint64) (domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByName", ctx, categoryName, userID)
	ret0, _ := ret[0].(domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByName indicates an expected call of GetCategoryByName.
func (mr *MockCategoryCacheMockRecorder) GetCategoryByName(ctx, categoryName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByName", reflect.TypeOf((*MockCategoryCache)(nil).GetCategoryByName), ctx, categoryName, userID)
}

// GetCategoryList mocks base method.
func (m *MockCategoryCache) GetCategoryList(ctx context.Context, userID uint64) ([]domain.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryList", ctx, userID)
	ret0, _ := ret[0].([]domain.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryList indicates an expected call of GetCategoryList.
func (mr *MockCategoryCacheMockRecorder) GetCategoryList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryList", reflect.TypeOf((*MockCategoryCache)(nil).GetCategoryList), ctx, userID)
}

// SaveCategory mocks base method.
func (m *MockCategoryCache) SaveCategory(ctx context.Context, category domain.Category, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCategory", ctx, category, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCategory indicates an expected call of SaveCategory.
func (mr *MockCategoryCacheMockRecorder) SaveCategory(ctx, category, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCategory", reflect.TypeOf((*MockCategoryCache)(nil).SaveCategory), ctx, category, expiration)
}

// SaveCategoryByName mocks base method.
func (m *MockCategoryCache) SaveCategoryByName(ctx context.Context, category domain.Category, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCategoryByName", ctx, category, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCategoryByName indicates an expected call of SaveCategoryByName.
func (mr *MockCategoryCacheMockRecorder) SaveCategoryByName(ctx, category, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCategoryByName", reflect.TypeOf((*MockCategoryCache)(nil).SaveCategoryByName), ctx, category, expiration)
}

// SaveCategoryList mocks base method.
func (m *MockCategoryCache) SaveCategoryList(ctx context.Context, userID uint64, categories []domain.Category, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCategoryList", ctx, userID, categories, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCategoryList indicates an expected call of SaveCategoryList.
func (mr *MockCategoryCacheMockRecorder) SaveCategoryList(ctx, userID, categories, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCategoryList", reflect.TypeOf((*MockCategoryCache)(nil).SaveCategoryList), ctx, userID, categories, expiration)
}
