// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/chat_history_cache.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/chat_history_cache.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/chat_history_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lechitz/aion-api/internal/chat/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatHistoryCache is a mock of ChatHistoryCache interface.
type MockChatHistoryCache struct {
	ctrl     *gomock.Controller
	recorder *MockChatHistoryCacheMockRecorder
	isgomock struct{}
}

// MockChatHistoryCacheMockRecorder is the mock recorder for MockChatHistoryCache.
type MockChatHistoryCacheMockRecorder struct {
	mock *MockChatHistoryCache
}

// NewMockChatHistoryCache creates a new mock instance.
func NewMockChatHistoryCache(ctrl *gomock.Controller) *MockChatHistoryCache {
	mock := &MockChatHistoryCache{ctrl: ctrl}
	mock.recorder = &MockChatHistoryCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatHistoryCache) EXPECT() *MockChatHistoryCacheMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockChatHistoryCache) Add(ctx context.Context, userID uint64, history domain.ChatHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, userID, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockChatHistoryCacheMockRecorder) Add(ctx, userID, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockChatHistoryCache)(nil).Add), ctx, userID, history)
}

// Clear mocks base method.
func (m *MockChatHistoryCache) Clear(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockChatHistoryCacheMockRecorder) Clear(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockChatHistoryCache)(nil).Clear), ctx, userID)
}

// GetLatest mocks base method.
func (m *MockChatHistoryCache) GetLatest(ctx context.Context, userID uint64, limit int) ([]domain.ChatHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ChatHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockChatHistoryCacheMockRecorder) GetLatest(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockChatHistoryCache)(nil).GetLatest), ctx, userID, limit)
}
