// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/chat_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/chat/core/ports/output/chat_history_repository.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/chat_history_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/lechitz/aion-api/internal/chat/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatHistoryRepository is a mock of ChatHistoryRepository interface.
type MockChatHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockChatHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockChatHistoryRepositoryMockRecorder is the mock recorder for MockChatHistoryRepository.
type MockChatHistoryRepositoryMockRecorder struct {
	mock *MockChatHistoryRepository
}

// NewMockChatHistoryRepository creates a new mock instance.
func NewMockChatHistoryRepository(ctrl *gomock.Controller) *MockChatHistoryRepository {
	mock := &MockChatHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockChatHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatHistoryRepository) EXPECT() *MockChatHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockChatHistoryRepository) GetByUserID(ctx context.Context, userID uint64, limit, offset int) ([]domain.ChatHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]domain.ChatHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockChatHistoryRepositoryMockRecorder) GetByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockChatHistoryRepository)(nil).GetByUserID), ctx, userID, limit, offset)
}

// GetLatest mocks base method.
func (m *MockChatHistoryRepository) GetLatest(ctx context.Context, userID uint64, limit int) ([]domain.ChatHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatest", ctx, userID, limit)
	ret0, _ := ret[0].([]domain.ChatHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatest indicates an expected call of GetLatest.
func (mr *MockChatHistoryRepositoryMockRecorder) GetLatest(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatest", reflect.TypeOf((*MockChatHistoryRepository)(nil).GetLatest), ctx, userID, limit)
}

// Save mocks base method.
func (m *MockChatHistoryRepository) Save(ctx context.Context, chatHistory domain.ChatHistory) (domain.ChatHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, chatHistory)
	ret0, _ := ret[0].(domain.ChatHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockChatHistoryRepositoryMockRecorder) Save(ctx, chatHistory any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockChatHistoryRepository)(nil).Save), ctx, chatHistory)
}
