// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/eventoutbox/core/ports/output/event_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/eventoutbox/core/ports/output/event_repository.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/event_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/aion-api/internal/eventoutbox/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// ListPending mocks base method.
func (m *MockEventRepository) ListPending(ctx context.Context, limit int) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx, limit)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockEventRepositoryMockRecorder) ListPending(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockEventRepository)(nil).ListPending), ctx, limit)
}

// MarkPublished mocks base method.
func (m *MockEventRepository) MarkPublished(ctx context.Context, eventID string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, eventID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockEventRepositoryMockRecorder) MarkPublished(ctx, eventID, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockEventRepository)(nil).MarkPublished), ctx, eventID, publishedAt)
}

// Reschedule mocks base method.
func (m *MockEventRepository) Reschedule(ctx context.Context, eventID string, nextAvailableAt time.Time, lastError string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reschedule", ctx, eventID, nextAvailableAt, lastError)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reschedule indicates an expected call of Reschedule.
func (mr *MockEventRepositoryMockRecorder) Reschedule(ctx, eventID, nextAvailableAt, lastError any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reschedule", reflect.TypeOf((*MockEventRepository)(nil).Reschedule), ctx, eventID, nextAvailableAt, lastError)
}

// Save mocks base method.
func (m *MockEventRepository) Save(ctx context.Context, event domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEventRepositoryMockRecorder) Save(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventRepository)(nil).Save), ctx, event)
}
