// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/AionApi/internal/platform/ports/output/logger/logger_output.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/AionApi/internal/platform/ports/output/logger/logger_output.go -destination=/home/lechitz/Projetos/AionApi/tests/mocks/logger_output_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContextLogger is a mock of ContextLogger interface.
type MockContextLogger struct {
	ctrl     *gomock.Controller
	recorder *MockContextLoggerMockRecorder
	isgomock struct{}
}

// MockContextLoggerMockRecorder is the mock recorder for MockContextLogger.
type MockContextLoggerMockRecorder struct {
	mock *MockContextLogger
}

// NewMockContextLogger creates a new mock instance.
func NewMockContextLogger(ctrl *gomock.Controller) *MockContextLogger {
	mock := &MockContextLogger{ctrl: ctrl}
	mock.recorder = &MockContextLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextLogger) EXPECT() *MockContextLoggerMockRecorder {
	return m.recorder
}

// Debugf mocks base method.
func (m *MockContextLogger) Debugf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockContextLoggerMockRecorder) Debugf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockContextLogger)(nil).Debugf), varargs...)
}

// Debugw mocks base method.
func (m *MockContextLogger) Debugw(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugw", varargs...)
}

// Debugw indicates an expected call of Debugw.
func (mr *MockContextLoggerMockRecorder) Debugw(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugw", reflect.TypeOf((*MockContextLogger)(nil).Debugw), varargs...)
}

// DebugwCtx mocks base method.
func (m *MockContextLogger) DebugwCtx(ctx context.Context, msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DebugwCtx", varargs...)
}

// DebugwCtx indicates an expected call of DebugwCtx.
func (mr *MockContextLoggerMockRecorder) DebugwCtx(ctx, msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DebugwCtx", reflect.TypeOf((*MockContextLogger)(nil).DebugwCtx), varargs...)
}

// Errorf mocks base method.
func (m *MockContextLogger) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockContextLoggerMockRecorder) Errorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockContextLogger)(nil).Errorf), varargs...)
}

// Errorw mocks base method.
func (m *MockContextLogger) Errorw(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorw", varargs...)
}

// Errorw indicates an expected call of Errorw.
func (mr *MockContextLoggerMockRecorder) Errorw(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorw", reflect.TypeOf((*MockContextLogger)(nil).Errorw), varargs...)
}

// ErrorwCtx mocks base method.
func (m *MockContextLogger) ErrorwCtx(ctx context.Context, msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorwCtx", varargs...)
}

// ErrorwCtx indicates an expected call of ErrorwCtx.
func (mr *MockContextLoggerMockRecorder) ErrorwCtx(ctx, msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorwCtx", reflect.TypeOf((*MockContextLogger)(nil).ErrorwCtx), varargs...)
}

// Infof mocks base method.
func (m *MockContextLogger) Infof(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockContextLoggerMockRecorder) Infof(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockContextLogger)(nil).Infof), varargs...)
}

// Infow mocks base method.
func (m *MockContextLogger) Infow(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infow", varargs...)
}

// Infow indicates an expected call of Infow.
func (mr *MockContextLoggerMockRecorder) Infow(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infow", reflect.TypeOf((*MockContextLogger)(nil).Infow), varargs...)
}

// InfowCtx mocks base method.
func (m *MockContextLogger) InfowCtx(ctx context.Context, msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfowCtx", varargs...)
}

// InfowCtx indicates an expected call of InfowCtx.
func (mr *MockContextLoggerMockRecorder) InfowCtx(ctx, msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfowCtx", reflect.TypeOf((*MockContextLogger)(nil).InfowCtx), varargs...)
}

// Warnf mocks base method.
func (m *MockContextLogger) Warnf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockContextLoggerMockRecorder) Warnf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockContextLogger)(nil).Warnf), varargs...)
}

// Warnw mocks base method.
func (m *MockContextLogger) Warnw(msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnw", varargs...)
}

// Warnw indicates an expected call of Warnw.
func (mr *MockContextLoggerMockRecorder) Warnw(msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnw", reflect.TypeOf((*MockContextLogger)(nil).Warnw), varargs...)
}

// WarnwCtx mocks base method.
func (m *MockContextLogger) WarnwCtx(ctx context.Context, msg string, keysAndValues ...any) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range keysAndValues {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnwCtx", varargs...)
}

// WarnwCtx indicates an expected call of WarnwCtx.
func (mr *MockContextLoggerMockRecorder) WarnwCtx(ctx, msg any, keysAndValues ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, keysAndValues...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnwCtx", reflect.TypeOf((*MockContextLogger)(nil).WarnwCtx), varargs...)
}
