// Code generated by MockGen. DO NOT EDIT.
// Source: ports/output/security/token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	"github.com/lechitz/AionApi/internal/core/domain"
	"reflect"

	"github.com/golang/mock/gomock"
)

// MockITokenService is a mock of ITokenService interface.
type MockITokenService struct {
	ctrl     *gomock.Controller
	recorder *MockITokenServiceMockRecorder
}

// MockITokenServiceMockRecorder is the mock recorder for MockITokenService.
type MockITokenServiceMockRecorder struct {
	mock *MockITokenService
}

// NewMockITokenService creates a new mock instance.
func NewMockITokenService(ctrl *gomock.Controller) *MockITokenService {
	mock := &MockITokenService{ctrl: ctrl}
	mock.recorder = &MockITokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITokenService) EXPECT() *MockITokenServiceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockITokenService) Check(ctx domain.ContextControl, token string) (uint64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, token)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Check indicates an expected call of Check.
func (mr *MockITokenServiceMockRecorder) Check(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockITokenService)(nil).Check), ctx, token)
}

// Create mocks base method.
func (m *MockITokenService) Create(ctx domain.ContextControl, token domain.TokenDomain) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITokenServiceMockRecorder) Create(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITokenService)(nil).Create), ctx, token)
}

// Delete mocks base method.
func (m *MockITokenService) Delete(ctx domain.ContextControl, token domain.TokenDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockITokenServiceMockRecorder) Delete(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockITokenService)(nil).Delete), ctx, token)
}

// Save mocks base method.
func (m *MockITokenService) Save(ctx domain.ContextControl, token domain.TokenDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockITokenServiceMockRecorder) Save(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITokenService)(nil).Save), ctx, token)
}

// Update mocks base method.
func (m *MockITokenService) Update(ctx domain.ContextControl, token domain.TokenDomain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockITokenServiceMockRecorder) Update(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockITokenService)(nil).Update), ctx, token)
}
