// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/AionApi/internal/record/core/ports/output/record_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/AionApi/internal/record/core/ports/output/record_repository.go -destination=/home/lechitz/Projetos/github/AionApi/tests/mocks/record_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/AionApi/internal/record/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordRepository is a mock of RecordRepository interface.
type MockRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockRecordRepositoryMockRecorder is the mock recorder for MockRecordRepository.
type MockRecordRepositoryMockRecorder struct {
	mock *MockRecordRepository
}

// NewMockRecordRepository creates a new mock instance.
func NewMockRecordRepository(ctrl *gomock.Controller) *MockRecordRepository {
	mock := &MockRecordRepository{ctrl: ctrl}
	mock.recorder = &MockRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordRepository) EXPECT() *MockRecordRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecordRepository) Create(ctx context.Context, r domain.Record) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecordRepositoryMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecordRepository)(nil).Create), ctx, r)
}

// Delete mocks base method.
func (m *MockRecordRepository) Delete(ctx context.Context, id, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordRepository)(nil).Delete), ctx, id, userID)
}

// DeleteAllByUser mocks base method.
func (m *MockRecordRepository) DeleteAllByUser(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllByUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllByUser indicates an expected call of DeleteAllByUser.
func (mr *MockRecordRepositoryMockRecorder) DeleteAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllByUser", reflect.TypeOf((*MockRecordRepository)(nil).DeleteAllByUser), ctx, userID)
}

// GetByID mocks base method.
func (m *MockRecordRepository) GetByID(ctx context.Context, recordID, userID uint64) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, recordID, userID)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRecordRepositoryMockRecorder) GetByID(ctx, recordID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRecordRepository)(nil).GetByID), ctx, recordID, userID)
}

// GetByUserCategoryDate mocks base method.
func (m *MockRecordRepository) GetByUserCategoryDate(ctx context.Context, userID, categoryID uint64, date time.Time) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserCategoryDate", ctx, userID, categoryID, date)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserCategoryDate indicates an expected call of GetByUserCategoryDate.
func (mr *MockRecordRepositoryMockRecorder) GetByUserCategoryDate(ctx, userID, categoryID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserCategoryDate", reflect.TypeOf((*MockRecordRepository)(nil).GetByUserCategoryDate), ctx, userID, categoryID, date)
}

// ListAllBetween mocks base method.
func (m *MockRecordRepository) ListAllBetween(ctx context.Context, userID uint64, startDate, endDate time.Time, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllBetween", ctx, userID, startDate, endDate, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllBetween indicates an expected call of ListAllBetween.
func (mr *MockRecordRepositoryMockRecorder) ListAllBetween(ctx, userID, startDate, endDate, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllBetween", reflect.TypeOf((*MockRecordRepository)(nil).ListAllBetween), ctx, userID, startDate, endDate, limit)
}

// ListAllUntil mocks base method.
func (m *MockRecordRepository) ListAllUntil(ctx context.Context, userID uint64, until time.Time, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUntil", ctx, userID, until, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUntil indicates an expected call of ListAllUntil.
func (mr *MockRecordRepositoryMockRecorder) ListAllUntil(ctx, userID, until, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUntil", reflect.TypeOf((*MockRecordRepository)(nil).ListAllUntil), ctx, userID, until, limit)
}

// ListByCategory mocks base method.
func (m *MockRecordRepository) ListByCategory(ctx context.Context, categoryID, userID uint64, limit int, afterEventTime *string, afterID *int64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCategory", ctx, categoryID, userID, limit, afterEventTime, afterID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCategory indicates an expected call of ListByCategory.
func (mr *MockRecordRepositoryMockRecorder) ListByCategory(ctx, categoryID, userID, limit, afterEventTime, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCategory", reflect.TypeOf((*MockRecordRepository)(nil).ListByCategory), ctx, categoryID, userID, limit, afterEventTime, afterID)
}

// ListByDay mocks base method.
func (m *MockRecordRepository) ListByDay(ctx context.Context, userID uint64, date time.Time) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDay", ctx, userID, date)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDay indicates an expected call of ListByDay.
func (mr *MockRecordRepositoryMockRecorder) ListByDay(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDay", reflect.TypeOf((*MockRecordRepository)(nil).ListByDay), ctx, userID, date)
}

// ListByTag mocks base method.
func (m *MockRecordRepository) ListByTag(ctx context.Context, tagID, userID uint64, limit int) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTag", ctx, tagID, userID, limit)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTag indicates an expected call of ListByTag.
func (mr *MockRecordRepositoryMockRecorder) ListByTag(ctx, tagID, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTag", reflect.TypeOf((*MockRecordRepository)(nil).ListByTag), ctx, tagID, userID, limit)
}

// ListByUser mocks base method.
func (m *MockRecordRepository) ListByUser(ctx context.Context, userID uint64, limit int, afterEventTime *string, afterID *int64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, afterEventTime, afterID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockRecordRepositoryMockRecorder) ListByUser(ctx, userID, limit, afterEventTime, afterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockRecordRepository)(nil).ListByUser), ctx, userID, limit, afterEventTime, afterID)
}

// Update mocks base method.
func (m *MockRecordRepository) Update(ctx context.Context, r domain.Record) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, r)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecordRepositoryMockRecorder) Update(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordRepository)(nil).Update), ctx, r)
}
