// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/record/core/ports/output/record_cache.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/record/core/ports/output/record_cache.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/record_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/aion-api/internal/record/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordCache is a mock of RecordCache interface.
type MockRecordCache struct {
	ctrl     *gomock.Controller
	recorder *MockRecordCacheMockRecorder
	isgomock struct{}
}

// MockRecordCacheMockRecorder is the mock recorder for MockRecordCache.
type MockRecordCacheMockRecorder struct {
	mock *MockRecordCache
}

// NewMockRecordCache creates a new mock instance.
func NewMockRecordCache(ctrl *gomock.Controller) *MockRecordCache {
	mock := &MockRecordCache{ctrl: ctrl}
	mock.recorder = &MockRecordCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordCache) EXPECT() *MockRecordCacheMockRecorder {
	return m.recorder
}

// DeleteRecord mocks base method.
func (m *MockRecordCache) DeleteRecord(ctx context.Context, recordID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecord", ctx, recordID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecord indicates an expected call of DeleteRecord.
func (mr *MockRecordCacheMockRecorder) DeleteRecord(ctx, recordID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecord", reflect.TypeOf((*MockRecordCache)(nil).DeleteRecord), ctx, recordID, userID)
}

// DeleteRecordsByCategory mocks base method.
func (m *MockRecordCache) DeleteRecordsByCategory(ctx context.Context, categoryID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordsByCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordsByCategory indicates an expected call of DeleteRecordsByCategory.
func (mr *MockRecordCacheMockRecorder) DeleteRecordsByCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordsByCategory", reflect.TypeOf((*MockRecordCache)(nil).DeleteRecordsByCategory), ctx, categoryID, userID)
}

// DeleteRecordsByDay mocks base method.
func (m *MockRecordCache) DeleteRecordsByDay(ctx context.Context, userID uint64, date time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordsByDay", ctx, userID, date)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordsByDay indicates an expected call of DeleteRecordsByDay.
func (mr *MockRecordCacheMockRecorder) DeleteRecordsByDay(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordsByDay", reflect.TypeOf((*MockRecordCache)(nil).DeleteRecordsByDay), ctx, userID, date)
}

// DeleteRecordsByTag mocks base method.
func (m *MockRecordCache) DeleteRecordsByTag(ctx context.Context, tagID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordsByTag", ctx, tagID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordsByTag indicates an expected call of DeleteRecordsByTag.
func (mr *MockRecordCacheMockRecorder) DeleteRecordsByTag(ctx, tagID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordsByTag", reflect.TypeOf((*MockRecordCache)(nil).DeleteRecordsByTag), ctx, tagID, userID)
}

// GetRecord mocks base method.
func (m *MockRecordCache) GetRecord(ctx context.Context, recordID, userID uint64) (domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", ctx, recordID, userID)
	ret0, _ := ret[0].(domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockRecordCacheMockRecorder) GetRecord(ctx, recordID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockRecordCache)(nil).GetRecord), ctx, recordID, userID)
}

// GetRecordsByCategory mocks base method.
func (m *MockRecordCache) GetRecordsByCategory(ctx context.Context, categoryID, userID uint64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByCategory indicates an expected call of GetRecordsByCategory.
func (mr *MockRecordCacheMockRecorder) GetRecordsByCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByCategory", reflect.TypeOf((*MockRecordCache)(nil).GetRecordsByCategory), ctx, categoryID, userID)
}

// GetRecordsByDay mocks base method.
func (m *MockRecordCache) GetRecordsByDay(ctx context.Context, userID uint64, date time.Time) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByDay", ctx, userID, date)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByDay indicates an expected call of GetRecordsByDay.
func (mr *MockRecordCacheMockRecorder) GetRecordsByDay(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByDay", reflect.TypeOf((*MockRecordCache)(nil).GetRecordsByDay), ctx, userID, date)
}

// GetRecordsByTag mocks base method.
func (m *MockRecordCache) GetRecordsByTag(ctx context.Context, tagID, userID uint64) ([]domain.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordsByTag", ctx, tagID, userID)
	ret0, _ := ret[0].([]domain.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordsByTag indicates an expected call of GetRecordsByTag.
func (mr *MockRecordCacheMockRecorder) GetRecordsByTag(ctx, tagID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordsByTag", reflect.TypeOf((*MockRecordCache)(nil).GetRecordsByTag), ctx, tagID, userID)
}

// SaveRecord mocks base method.
func (m *MockRecordCache) SaveRecord(ctx context.Context, record domain.Record, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecord", ctx, record, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecord indicates an expected call of SaveRecord.
func (mr *MockRecordCacheMockRecorder) SaveRecord(ctx, record, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecord", reflect.TypeOf((*MockRecordCache)(nil).SaveRecord), ctx, record, expiration)
}

// SaveRecordsByCategory mocks base method.
func (m *MockRecordCache) SaveRecordsByCategory(ctx context.Context, categoryID, userID uint64, records []domain.Record, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecordsByCategory", ctx, categoryID, userID, records, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecordsByCategory indicates an expected call of SaveRecordsByCategory.
func (mr *MockRecordCacheMockRecorder) SaveRecordsByCategory(ctx, categoryID, userID, records, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecordsByCategory", reflect.TypeOf((*MockRecordCache)(nil).SaveRecordsByCategory), ctx, categoryID, userID, records, expiration)
}

// SaveRecordsByDay mocks base method.
func (m *MockRecordCache) SaveRecordsByDay(ctx context.Context, userID uint64, date time.Time, records []domain.Record, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecordsByDay", ctx, userID, date, records, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecordsByDay indicates an expected call of SaveRecordsByDay.
func (mr *MockRecordCacheMockRecorder) SaveRecordsByDay(ctx, userID, date, records, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecordsByDay", reflect.TypeOf((*MockRecordCache)(nil).SaveRecordsByDay), ctx, userID, date, records, expiration)
}

// SaveRecordsByTag mocks base method.
func (m *MockRecordCache) SaveRecordsByTag(ctx context.Context, tagID, userID uint64, records []domain.Record, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecordsByTag", ctx, tagID, userID, records, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecordsByTag indicates an expected call of SaveRecordsByTag.
func (mr *MockRecordCacheMockRecorder) SaveRecordsByTag(ctx, tagID, userID, records, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecordsByTag", reflect.TypeOf((*MockRecordCache)(nil).SaveRecordsByTag), ctx, tagID, userID, records, expiration)
}
