// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/user/core/ports/output/registration_session_output.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/user/core/ports/output/registration_session_output.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/registration_session_output_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/aion-api/internal/user/core/domain"
	output "github.com/lechitz/aion-api/internal/user/core/ports/output"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationSessionRepository is a mock of RegistrationSessionRepository interface.
type MockRegistrationSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockRegistrationSessionRepositoryMockRecorder is the mock recorder for MockRegistrationSessionRepository.
type MockRegistrationSessionRepositoryMockRecorder struct {
	mock *MockRegistrationSessionRepository
}

// NewMockRegistrationSessionRepository creates a new mock instance.
func NewMockRegistrationSessionRepository(ctrl *gomock.Controller) *MockRegistrationSessionRepository {
	mock := &MockRegistrationSessionRepository{ctrl: ctrl}
	mock.recorder = &MockRegistrationSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationSessionRepository) EXPECT() *MockRegistrationSessionRepositoryMockRecorder {
	return m.recorder
}

// CheckRegistrationUniqueness mocks base method.
func (m *MockRegistrationSessionRepository) CheckRegistrationUniqueness(ctx context.Context, username, email string, now time.Time) (output.RegistrationSessionUniqueness, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRegistrationUniqueness", ctx, username, email, now)
	ret0, _ := ret[0].(output.RegistrationSessionUniqueness)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRegistrationUniqueness indicates an expected call of CheckRegistrationUniqueness.
func (mr *MockRegistrationSessionRepositoryMockRecorder) CheckRegistrationUniqueness(ctx, username, email, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRegistrationUniqueness", reflect.TypeOf((*MockRegistrationSessionRepository)(nil).CheckRegistrationUniqueness), ctx, username, email, now)
}

// CreateRegistrationSession mocks base method.
func (m *MockRegistrationSessionRepository) CreateRegistrationSession(ctx context.Context, session domain.RegistrationSession) (domain.RegistrationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistrationSession", ctx, session)
	ret0, _ := ret[0].(domain.RegistrationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistrationSession indicates an expected call of CreateRegistrationSession.
func (mr *MockRegistrationSessionRepositoryMockRecorder) CreateRegistrationSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistrationSession", reflect.TypeOf((*MockRegistrationSessionRepository)(nil).CreateRegistrationSession), ctx, session)
}

// DeleteRegistrationSession mocks base method.
func (m *MockRegistrationSessionRepository) DeleteRegistrationSession(ctx context.Context, registrationID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistrationSession", ctx, registrationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistrationSession indicates an expected call of DeleteRegistrationSession.
func (mr *MockRegistrationSessionRepositoryMockRecorder) DeleteRegistrationSession(ctx, registrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistrationSession", reflect.TypeOf((*MockRegistrationSessionRepository)(nil).DeleteRegistrationSession), ctx, registrationID)
}

// GetRegistrationSessionByID mocks base method.
func (m *MockRegistrationSessionRepository) GetRegistrationSessionByID(ctx context.Context, registrationID string) (domain.RegistrationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationSessionByID", ctx, registrationID)
	ret0, _ := ret[0].(domain.RegistrationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationSessionByID indicates an expected call of GetRegistrationSessionByID.
func (mr *MockRegistrationSessionRepositoryMockRecorder) GetRegistrationSessionByID(ctx, registrationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationSessionByID", reflect.TypeOf((*MockRegistrationSessionRepository)(nil).GetRegistrationSessionByID), ctx, registrationID)
}

// UpdateRegistrationSession mocks base method.
func (m *MockRegistrationSessionRepository) UpdateRegistrationSession(ctx context.Context, registrationID string, fields map[string]any) (domain.RegistrationSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRegistrationSession", ctx, registrationID, fields)
	ret0, _ := ret[0].(domain.RegistrationSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRegistrationSession indicates an expected call of UpdateRegistrationSession.
func (mr *MockRegistrationSessionRepositoryMockRecorder) UpdateRegistrationSession(ctx, registrationID, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRegistrationSession", reflect.TypeOf((*MockRegistrationSessionRepository)(nil).UpdateRegistrationSession), ctx, registrationID, fields)
}
