// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/AionApi/internal/admin/core/ports/output/role_assigner.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/AionApi/internal/admin/core/ports/output/role_assigner.go -destination=/home/lechitz/Projetos/github/Aion/AionApi/tests/mocks/role_assigner_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoleAssigner is a mock of RoleAssigner interface.
type MockRoleAssigner struct {
	ctrl     *gomock.Controller
	recorder *MockRoleAssignerMockRecorder
	isgomock struct{}
}

// MockRoleAssignerMockRecorder is the mock recorder for MockRoleAssigner.
type MockRoleAssignerMockRecorder struct {
	mock *MockRoleAssigner
}

// NewMockRoleAssigner creates a new mock instance.
func NewMockRoleAssigner(ctrl *gomock.Controller) *MockRoleAssigner {
	mock := &MockRoleAssigner{ctrl: ctrl}
	mock.recorder = &MockRoleAssignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleAssigner) EXPECT() *MockRoleAssignerMockRecorder {
	return m.recorder
}

// AssignDefaultRole mocks base method.
func (m *MockRoleAssigner) AssignDefaultRole(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDefaultRole", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDefaultRole indicates an expected call of AssignDefaultRole.
func (mr *MockRoleAssignerMockRecorder) AssignDefaultRole(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDefaultRole", reflect.TypeOf((*MockRoleAssigner)(nil).AssignDefaultRole), ctx, userID)
}
