// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/aion-api/internal/admin/core/ports/output/role_cache_invalidator.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/aion-api/internal/admin/core/ports/output/role_cache_invalidator.go -destination=/home/lechitz/Projetos/github/Aion/aion-api/tests/mocks/role_cache_invalidator_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoleCacheInvalidator is a mock of RoleCacheInvalidator interface.
type MockRoleCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockRoleCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockRoleCacheInvalidatorMockRecorder is the mock recorder for MockRoleCacheInvalidator.
type MockRoleCacheInvalidatorMockRecorder struct {
	mock *MockRoleCacheInvalidator
}

// NewMockRoleCacheInvalidator creates a new mock instance.
func NewMockRoleCacheInvalidator(ctrl *gomock.Controller) *MockRoleCacheInvalidator {
	mock := &MockRoleCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockRoleCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleCacheInvalidator) EXPECT() *MockRoleCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateRoles mocks base method.
func (m *MockRoleCacheInvalidator) InvalidateRoles(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateRoles", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateRoles indicates an expected call of InvalidateRoles.
func (mr *MockRoleCacheInvalidatorMockRecorder) InvalidateRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateRoles", reflect.TypeOf((*MockRoleCacheInvalidator)(nil).InvalidateRoles), ctx, userID)
}
