// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lechitz/Projetos/github/Aion/AionApi/internal/tag/core/ports/output/tag_cache.go
//
// Generated by this command:
//
//	mockgen -source=/home/lechitz/Projetos/github/Aion/AionApi/internal/tag/core/ports/output/tag_cache.go -destination=/home/lechitz/Projetos/github/Aion/AionApi/tests/mocks/tag_cache_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/lechitz/AionApi/internal/tag/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockTagCache is a mock of TagCache interface.
type MockTagCache struct {
	ctrl     *gomock.Controller
	recorder *MockTagCacheMockRecorder
	isgomock struct{}
}

// MockTagCacheMockRecorder is the mock recorder for MockTagCache.
type MockTagCacheMockRecorder struct {
	mock *MockTagCache
}

// NewMockTagCache creates a new mock instance.
func NewMockTagCache(ctrl *gomock.Controller) *MockTagCache {
	mock := &MockTagCache{ctrl: ctrl}
	mock.recorder = &MockTagCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagCache) EXPECT() *MockTagCacheMockRecorder {
	return m.recorder
}

// DeleteTag mocks base method.
func (m *MockTagCache) DeleteTag(ctx context.Context, tagID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, tagID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockTagCacheMockRecorder) DeleteTag(ctx, tagID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockTagCache)(nil).DeleteTag), ctx, tagID, userID)
}

// DeleteTagByName mocks base method.
func (m *MockTagCache) DeleteTagByName(ctx context.Context, tagName string, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagByName", ctx, tagName, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTagByName indicates an expected call of DeleteTagByName.
func (mr *MockTagCacheMockRecorder) DeleteTagByName(ctx, tagName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagByName", reflect.TypeOf((*MockTagCache)(nil).DeleteTagByName), ctx, tagName, userID)
}

// DeleteTagList mocks base method.
func (m *MockTagCache) DeleteTagList(ctx context.Context, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagList", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTagList indicates an expected call of DeleteTagList.
func (mr *MockTagCacheMockRecorder) DeleteTagList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagList", reflect.TypeOf((*MockTagCache)(nil).DeleteTagList), ctx, userID)
}

// DeleteTagsByCategory mocks base method.
func (m *MockTagCache) DeleteTagsByCategory(ctx context.Context, categoryID, userID uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTagsByCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTagsByCategory indicates an expected call of DeleteTagsByCategory.
func (mr *MockTagCacheMockRecorder) DeleteTagsByCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTagsByCategory", reflect.TypeOf((*MockTagCache)(nil).DeleteTagsByCategory), ctx, categoryID, userID)
}

// GetTag mocks base method.
func (m *MockTagCache) GetTag(ctx context.Context, tagID, userID uint64) (domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", ctx, tagID, userID)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockTagCacheMockRecorder) GetTag(ctx, tagID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockTagCache)(nil).GetTag), ctx, tagID, userID)
}

// GetTagByName mocks base method.
func (m *MockTagCache) GetTagByName(ctx context.Context, tagName string, userID uint64) (domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagByName", ctx, tagName, userID)
	ret0, _ := ret[0].(domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagByName indicates an expected call of GetTagByName.
func (mr *MockTagCacheMockRecorder) GetTagByName(ctx, tagName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagByName", reflect.TypeOf((*MockTagCache)(nil).GetTagByName), ctx, tagName, userID)
}

// GetTagList mocks base method.
func (m *MockTagCache) GetTagList(ctx context.Context, userID uint64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagList", ctx, userID)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagList indicates an expected call of GetTagList.
func (mr *MockTagCacheMockRecorder) GetTagList(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagList", reflect.TypeOf((*MockTagCache)(nil).GetTagList), ctx, userID)
}

// GetTagsByCategory mocks base method.
func (m *MockTagCache) GetTagsByCategory(ctx context.Context, categoryID, userID uint64) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagsByCategory", ctx, categoryID, userID)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagsByCategory indicates an expected call of GetTagsByCategory.
func (mr *MockTagCacheMockRecorder) GetTagsByCategory(ctx, categoryID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagsByCategory", reflect.TypeOf((*MockTagCache)(nil).GetTagsByCategory), ctx, categoryID, userID)
}

// SaveTag mocks base method.
func (m *MockTagCache) SaveTag(ctx context.Context, tag domain.Tag, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTag", ctx, tag, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTag indicates an expected call of SaveTag.
func (mr *MockTagCacheMockRecorder) SaveTag(ctx, tag, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTag", reflect.TypeOf((*MockTagCache)(nil).SaveTag), ctx, tag, expiration)
}

// SaveTagByName mocks base method.
func (m *MockTagCache) SaveTagByName(ctx context.Context, tag domain.Tag, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTagByName", ctx, tag, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTagByName indicates an expected call of SaveTagByName.
func (mr *MockTagCacheMockRecorder) SaveTagByName(ctx, tag, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTagByName", reflect.TypeOf((*MockTagCache)(nil).SaveTagByName), ctx, tag, expiration)
}

// SaveTagList mocks base method.
func (m *MockTagCache) SaveTagList(ctx context.Context, userID uint64, tags []domain.Tag, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTagList", ctx, userID, tags, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTagList indicates an expected call of SaveTagList.
func (mr *MockTagCacheMockRecorder) SaveTagList(ctx, userID, tags, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTagList", reflect.TypeOf((*MockTagCache)(nil).SaveTagList), ctx, userID, tags, expiration)
}

// SaveTagsByCategory mocks base method.
func (m *MockTagCache) SaveTagsByCategory(ctx context.Context, categoryID, userID uint64, tags []domain.Tag, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTagsByCategory", ctx, categoryID, userID, tags, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTagsByCategory indicates an expected call of SaveTagsByCategory.
func (mr *MockTagCacheMockRecorder) SaveTagsByCategory(ctx, categoryID, userID, tags, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTagsByCategory", reflect.TypeOf((*MockTagCache)(nil).SaveTagsByCategory), ctx, categoryID, userID, tags, expiration)
}
