version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-prod
    restart: always
    env_file:
      - .env.prod
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
      - ./internal/infrastructure/db/postgres/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis-aion-prod
    ports:
      - "6379:6379"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  aion-api:
    image: aion-api:prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aion-api-prod
    env_file:
      - .env.prod
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rede_local

networks:
  rede_local:

volumes:
  postgres-data-prod:
