version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./internal/adapters/secondary/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis-aion-dev
    ports:
      - "6379:6379"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.101.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./infra/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4318:4318"       # OTLP HTTP (AionAPI envia para esse)
      - "55681:55681"     # OTLP gRPC (opcional, legado)
      - "9888:9888"     # Expondo /metrics para Prometheus scrape (ajustado aqui)
    networks:
      - rede_local
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./infra/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - rede_local
    depends_on:
      - otel-collector

  aion-api:
    image: aion-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aion-api-dev
    env_file:
      - .env.dev
    ports:
      - "5001:5001" # REST
      - "8081:8081" # GraphQL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel-collector:
        condition: service_started
    networks:
      - rede_local
    restart: unless-stopped

networks:
  rede_local:

volumes:
  postgres-data-dev:
