version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-prod
    # ...
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
      - ./infra/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-aion-prod
    ports:
      - "6379:6379"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  aion-api:
    container_name: aion-api-prod
    image: aion-api:prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_TYPE=${DB_TYPE}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_ADDR=${REDIS_ADDR}
    ports:
      - "5001:5001"
    expose:
      - "5001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rede_local

networks:
  rede_local:

volumes:
  postgres-data-prod:
    driver: local
