version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    env_file:
      - .env.dev
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./adapters/secondary/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis-aion-dev
    ports:
      - "6379:6379"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  aion-api:
    image: aion-api:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aion-api-dev
    env_file:
      - .env.dev
    ports:
      - "5001:5001" # REST
      - "8081:8081" # GraphQL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rede_local
    restart: unless-stopped

networks:
  rede_local:

volumes:
  postgres-data-dev:
