version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-dev
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ./infra/db/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - rede_local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis-aion
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - rede_local
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  aion-api:
    container_name: aion-api-dev
    image: aion-api
    build: ${AION_GO_FOLDER}
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_TYPE=${DB_TYPE}
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_ADDR=${REDIS_ADDR}
    ports:
      - "5001:5001"
    expose:
      - "5001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rede_local

networks:
  rede_local:

volumes:
  postgres-data-dev:
    driver: local
