package constants

const (
	ErrorToValidateCreateUser = "error to validate create user"
	ErrorToHashPassword       = "error to hash password"
	ErrorToCreateUser         = "error to create user"
	SuccessUserCreated        = "user created successfully"
	ErrorToGetAllUsers        = "error to get all users"
	SuccessUsersRetrieved     = "users retrieved successfully"
	ErrorToGetUserByID        = "error to get user by id"
	SuccessUserRetrieved      = "user retrieved successfully"
	ErrorToGetUserByUserName  = "error to get user by username"
	ErrorToGetUserByEmail     = "error to get user by email"
	ErrorNoFieldsToUpdate     = "no fields to update"
	ErrorToUpdatePassword     = "error to update password"
	SuccessPasswordUpdated    = "password updated successfully"
	ErrorToSoftDeleteUser     = "error to soft delete user"
	SuccessUserSoftDeleted    = "user soft deleted successfully"
	NameIsRequired            = "name is required"
	UsernameIsRequired        = "username is required"
	EmailIsRequired           = "email is required"
	PasswordIsRequired        = "password is required"
	InvalidEmail              = "invalid email format"
	UsernameIsAlreadyInUse    = "username is already in use"
	EmailIsAlreadyInUse       = "email is already in use"
)
