// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/output/security/hasher_output.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/output/security/hasher_output.go -destination=tests/mocks/security/mock_security_store.go -package=securitymocks -mock_names=Store=MockSecurityStore
//

// Package securitymocks is a generated GoMock package.
package securitymocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSecurityStore is a mock of Store interface.
type MockSecurityStore struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityStoreMockRecorder
	isgomock struct{}
}

// MockSecurityStoreMockRecorder is the mock recorder for MockSecurityStore.
type MockSecurityStoreMockRecorder struct {
	mock *MockSecurityStore
}

// NewMockSecurityStore creates a new mock instance.
func NewMockSecurityStore(ctrl *gomock.Controller) *MockSecurityStore {
	mock := &MockSecurityStore{ctrl: ctrl}
	mock.recorder = &MockSecurityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityStore) EXPECT() *MockSecurityStoreMockRecorder {
	return m.recorder
}

// HashPassword mocks base method.
func (m *MockSecurityStore) HashPassword(plain string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", plain)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockSecurityStoreMockRecorder) HashPassword(plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockSecurityStore)(nil).HashPassword), plain)
}

// ValidatePassword mocks base method.
func (m *MockSecurityStore) ValidatePassword(hashed, plain string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatePassword", hashed, plain)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidatePassword indicates an expected call of ValidatePassword.
func (mr *MockSecurityStoreMockRecorder) ValidatePassword(hashed, plain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatePassword", reflect.TypeOf((*MockSecurityStore)(nil).ValidatePassword), hashed, plain)
}
