// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	CategoryID  string  `json:"category_id"`
	UserID      string  `json:"user_id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"color_hex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type DtoCreateCategory struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"color_hex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type DtoDeleteCategory struct {
	CategoryID string `json:"category_id"`
}

type DtoGetCategoryByID struct {
	CategoryID string `json:"category_id"`
}

type DtoGetCategoryByName struct {
	Name string `json:"name"`
}

type DtoUpdateCategory struct {
	CategoryID  string  `json:"category_id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"color_hex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type Mutation struct {
}

type NewTag struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CategoryID  string  `json:"category_id"`
}

type Query struct {
}

type Tags struct {
	TagID       string    `json:"tag_id"`
	Name        string    `json:"name"`
	CategoryID  *Category `json:"category_id"`
	Description *string   `json:"description,omitempty"`
}
