package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

import (
	"context"
	"errors"
	"strconv"

	"github.com/lechitz/AionApi/internal/adapters/primary/graph/constants"
	"github.com/lechitz/AionApi/internal/adapters/primary/graph/model"
	"github.com/lechitz/AionApi/internal/core/domain/entity"
	"github.com/lechitz/AionApi/internal/def"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, category model.DtoCreateCategory) (*model.Category, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartCreateCategory)
	defer span.End()

	span.AddEvent(constants.SpanEventCreateCategory, trace.WithAttributes(TraceAttributesFromCategory(category)...))

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return nil, err
	}

	createCategory := entity.Category{
		UserID:      userID,
		Name:        category.Name,
		Description: *category.Description,
		Color:       *category.ColorHex,
		Icon:        *category.Icon,
	}

	categoryDB, err := r.CategoryService.CreateCategory(ctx, createCategory)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return nil, err
	}

	span.SetAttributes(
		attribute.String(constants.CategoryName, categoryDB.Name),
		attribute.String(constants.UserID, strconv.FormatUint(categoryDB.UserID, 10)),
		attribute.String(constants.CategoryID, strconv.FormatUint(categoryDB.ID, 10)),
	)

	span.SetStatus(codes.Ok, constants.SuccessCategoryCreated)

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(userID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// CreateTag is the resolver for the CreateTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.NewTag) (*model.Tags, error) {
	_ = ctx
	_ = input
	return nil, errors.New("not implemented")
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, category model.DtoUpdateCategory) (*model.Category, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartUpdateCategory)
	defer span.End()

	span.AddEvent(constants.SpanEventUpdateCategory, trace.WithAttributes(attribute.String(constants.CategoryID, category.CategoryID)))

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return nil, err
	}

	categoryIDUint, err := strconv.ParseUint(category.CategoryID, 10, 64)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return nil, errors.New(constants.InvalidCategoryID)
	}

	span.SetAttributes(
		attribute.String(constants.UserID, strconv.FormatUint(userID, 10)),
		attribute.String(constants.CategoryID, category.CategoryID),
	)

	updateCategory := entity.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	if category.Name != nil {
		updateCategory.Name = *category.Name
	}
	if category.Description != nil {
		updateCategory.Description = *category.Description
	}
	if category.ColorHex != nil {
		updateCategory.Color = *category.ColorHex
	}
	if category.Icon != nil {
		updateCategory.Icon = *category.Icon
	}

	categoryDB, err := r.CategoryService.UpdateCategory(ctx, updateCategory)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return nil, err
	}

	span.SetAttributes(attribute.String(constants.CategoryName, categoryDB.Name))
	span.SetStatus(codes.Ok, constants.SuccessCategoryUpdated)

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(categoryDB.UserID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// SoftDeleteCategory is the resolver for the softDeleteCategory field.
func (r *mutationResolver) SoftDeleteCategory(ctx context.Context, category model.DtoDeleteCategory) (bool, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartSoftDeleteCategory)
	defer span.End()

	span.AddEvent(constants.SpanEventSoftDeleteCategory, trace.WithAttributes(attribute.String(constants.CategoryID, category.CategoryID)))

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return false, err
	}

	categoryIDUint, err := strconv.ParseUint(category.CategoryID, 10, 64)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return false, errors.New(constants.InvalidCategoryID)
	}

	span.SetAttributes(
		attribute.String(constants.UserID, strconv.FormatUint(userID, 10)),
		attribute.String(constants.CategoryID, category.CategoryID),
	)

	categoryDomain := entity.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	if err := r.CategoryService.SoftDeleteCategory(ctx, categoryDomain); err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return false, err
	}

	span.SetStatus(codes.Ok, constants.SuccessCategorySoftDeleted)
	return true, nil
}

// GetAllCategories is the resolver for the allCategories field.
func (r *queryResolver) GetAllCategories(ctx context.Context) ([]*model.Category, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartAllGetCategories)
	defer span.End()

	span.AddEvent(constants.SpanEventGetAllCategories)

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		r.Logger.Errorw(constants.ErrUserIDNotFound, def.Error, err.Error())
		return nil, err
	}

	span.SetAttributes(attribute.String(constants.UserID, strconv.FormatUint(userID, 10)))

	categoryDB, err := r.CategoryService.GetAllCategories(ctx, userID)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, constants.ErrAllCategoriesNotFound)
		return nil, errors.New(constants.ErrAllCategoriesNotFound)
	}

	categories := make([]*model.Category, len(categoryDB))
	for i, category := range categoryDB {
		categories[i] = &model.Category{
			CategoryID:  strconv.FormatUint(category.ID, 10),
			UserID:      strconv.FormatUint(userID, 10),
			Name:        category.Name,
			Description: &category.Description,
			ColorHex:    &category.Color,
			Icon:        &category.Icon,
		}
	}

	span.SetAttributes(attribute.Int(constants.CategoriesCount, len(categories)))
	span.SetStatus(codes.Ok, constants.SuccessAllCategoriesFetch)

	return categories, nil
}

// GetCategoryByID is the resolver for the getCategoryByID field.
func (r *queryResolver) GetCategoryByID(ctx context.Context, categoryRequest model.DtoGetCategoryByID) (*model.Category, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartGetCategoryByID)
	defer span.End()

	span.AddEvent(constants.SpanEventGetCategoryByID, trace.WithAttributes(attribute.String(constants.CategoryID, categoryRequest.CategoryID)))

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		r.Logger.Errorw(constants.ErrUserIDNotFound, def.Error, err.Error())
		return nil, err
	}

	span.SetAttributes(attribute.String(constants.UserID, strconv.FormatUint(userID, 10)))

	categoryIDUint, err := strconv.ParseUint(categoryRequest.CategoryID, 10, 64)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, constants.InvalidCategoryID)
		return nil, errors.New(constants.InvalidCategoryID)
	}

	span.SetAttributes(attribute.String(constants.CategoryID, categoryRequest.CategoryID))

	category := entity.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	categoryDB, err := r.CategoryService.GetCategoryByID(ctx, category)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, constants.ErrCategoryNotFound)
		return nil, err
	}

	span.SetStatus(codes.Ok, constants.SuccessCategoryFetch)
	span.SetAttributes(
		attribute.String(constants.CategoryName, categoryDB.Name),
		attribute.String(constants.CategoryColor, categoryDB.Color),
	)

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(categoryDB.UserID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// GetCategoryByName is the resolver for the getCategoryByName field.
func (r *queryResolver) GetCategoryByName(ctx context.Context, categoryRequest model.DtoGetCategoryByName) (*model.Category, error) {
	tracer := otel.Tracer(constants.TracerCategory)
	ctx, span := tracer.Start(ctx, constants.SpanStartGetCategoryByName)
	defer span.End()

	span.AddEvent(constants.SpanEventGetCategoryByName, trace.WithAttributes(attribute.String(constants.CategoryName, categoryRequest.Name)))

	userID, ok := ctx.Value(def.CtxUserID).(uint64)
	if !ok {
		err := errors.New(constants.ErrUserIDNotFound)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		r.Logger.Errorw(constants.ErrUserIDNotFound, def.Error, err.Error())
		return nil, err
	}

	span.SetAttributes(
		attribute.String(constants.UserID, strconv.FormatUint(userID, 10)),
		attribute.String(constants.CategoryName, categoryRequest.Name),
	)

	category := entity.Category{
		UserID: userID,
		Name:   categoryRequest.Name,
	}

	categoryDB, err := r.CategoryService.GetCategoryByName(ctx, category)
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, constants.ErrCategoryByNameNotFound)
		return nil, err
	}

	if categoryDB.Name == "" {
		span.SetStatus(codes.Ok, constants.ErrCategoryNotFound)
		return nil, errors.New(constants.ErrCategoryNotFound)
	}

	span.SetStatus(codes.Ok, constants.SuccessCategoryFetch)
	span.SetAttributes(
		attribute.String(constants.CategoryID, strconv.FormatUint(categoryDB.ID, 10)),
		attribute.String(constants.CategoryColor, categoryDB.Color),
	)

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(categoryDB.UserID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// GetAllTags is the resolver for the GetAllTags field.
func (r *queryResolver) GetAllTags(ctx context.Context) ([]*model.Tags, error) {
	_ = ctx
	return nil, errors.New("not implemented: GetAllTags - GetAllTags")
}

// GetTagByID is the resolver for the GetTagByID field.
func (r *queryResolver) GetTagByID(ctx context.Context, tagID string) (*model.Tags, error) {
	_ = ctx
	_ = tagID
	return nil, errors.New("not implemented: GetTagByID")
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
