// Package main provides a CLI helper for generating seed data and authentication tokens.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/lechitz/AionApi/internal/shared/constants/claimskeys"
	"golang.org/x/crypto/bcrypt"
)

const (
	defaultPassword = "testpassword123"
	jwtExpiration   = 24 * time.Hour
	bcryptCost      = 10
	envFileTemplate = `# Generated by seed-helper - DO NOT COMMIT
# Use these values for local seeding
USER_TOKEN_TEST='%s'
SEED_USER_COUNT=%d
DEV_PASSWORD='%s'
SECRET_KEY='%s'
JWT_TOKEN='%s'
`
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		os.Exit(1)
	}

	command := os.Args[1]

	switch command {
	case "generate-token":
		generateToken()
	case "generate-bcrypt":
		generateBcrypt()
	case "generate-env":
		generateEnvFile()
	default:
		_, _ = fmt.Fprintf(os.Stdout, "Unknown command: %s\n", command)
		printUsage()
		os.Exit(1)
	}
}

func printUsage() {
	_, _ = fmt.Fprintf(os.Stdout, `Seed Helper - Generate tokens and hashes for database seeding

Usage:
  seed-helper generate-token [userID] [secretKey]
    Generate a JWT token for testing (default: userID=1, secretKey from env or arg)
    
  seed-helper generate-bcrypt [password]
    Generate a bcrypt hash for a password (default: testpassword123)
    
  seed-helper generate-env [userCount] [secretKey]
    Generate a complete .env.local file with all seed variables
    
Examples:
  seed-helper generate-token 1 my-secret-key
  seed-helper generate-bcrypt testpassword123
  seed-helper generate-env 100 my-secret-key
`)
}

func generateToken() {
	userID := uint64(1)
	secretKey := getSecretKey()

	if len(os.Args) > 2 {
		id, err := strconv.ParseUint(os.Args[2], 10, 64)
		if err == nil {
			userID = id
		}
	}

	if len(os.Args) > 3 {
		secretKey = os.Args[3]
	}

	claims := jwt.MapClaims{
		claimskeys.UserID: strconv.FormatUint(userID, 10),
		claimskeys.Exp:    time.Now().Add(jwtExpiration).Unix(),
		claimskeys.Roles:  "user",
		claimskeys.Name:   fmt.Sprintf("Test User %d", userID),
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(secretKey))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating token: %v\n", err)
		os.Exit(1)
	}

	_, _ = fmt.Fprintf(os.Stdout, "JWT Token for user %d:\n%s\n\n", userID, tokenString)
	_, _ = fmt.Fprintf(os.Stdout, "Export to environment:\nexport JWT_TOKEN='%s'\n", tokenString)
}

func generateBcrypt() {
	password := defaultPassword
	if len(os.Args) > 2 {
		password = os.Args[2]
	}

	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcryptCost)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating bcrypt hash: %v\n", err)
		os.Exit(1)
	}

	_, _ = fmt.Fprintf(os.Stdout, "Bcrypt hash for password '%s':\n%s\n\n", password, string(hash))
	_, _ = fmt.Fprintf(os.Stdout, "Export to environment:\nexport USER_TOKEN_TEST='%s'\n", string(hash))
}

func generateEnvFile() {
	userCount := 10
	secretKey := getSecretKey()
	password := defaultPassword

	if len(os.Args) > 2 {
		count, err := strconv.Atoi(os.Args[2])
		if err == nil && count > 0 {
			userCount = count
		}
	}

	if len(os.Args) > 3 {
		secretKey = os.Args[3]
	}

	if len(os.Args) > 4 {
		password = os.Args[4]
	}

	// Generate bcrypt hash
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcryptCost)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating bcrypt hash: %v\n", err)
		os.Exit(1)
	}

	// Generate JWT token for user 1
	claims := jwt.MapClaims{
		claimskeys.UserID: "1",
		claimskeys.Exp:    time.Now().Add(jwtExpiration).Unix(),
		claimskeys.Roles:  "user",
		claimskeys.Name:   "Test User 1",
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	tokenString, err := token.SignedString([]byte(secretKey))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating token: %v\n", err)
		os.Exit(1)
	}

	// Create .env.local content
	envContent := fmt.Sprintf(envFileTemplate,
		string(hash),
		userCount,
		password,
		secretKey,
		tokenString,
	)

	// Write to file
	filePath := "infrastructure/db/seed/.env.local"
	if err := os.WriteFile(filePath, []byte(envContent), 0o600); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
		os.Exit(1)
	}

	_, _ = fmt.Fprintf(os.Stdout, "✅ Generated %s\n\n", filePath)
	_, _ = fmt.Fprintln(os.Stdout, "Configuration:")
	_, _ = fmt.Fprintf(os.Stdout, "  Users to seed: %d\n", userCount)
	_, _ = fmt.Fprintf(os.Stdout, "  Password: %s\n", password)
	_, _ = fmt.Fprintf(os.Stdout, "  Bcrypt hash: %s\n", string(hash))
	_, _ = fmt.Fprintf(os.Stdout, "\nTo use:\n")
	_, _ = fmt.Fprintf(os.Stdout, "  make seed-all-local\n")
	_, _ = fmt.Fprintf(os.Stdout, "\nOr export manually:\n")
	_, _ = fmt.Fprintf(os.Stdout, "  source %s\n", filePath)

	// Also print the JWT token info for API testing
	printTokenInfo(tokenString, secretKey)
}

func getSecretKey() string {
	// Try to get from environment first
	if key := os.Getenv("SECRET_KEY"); key != "" {
		return key
	}

	// Try to read from dev .env file
	devEnvPath := "infrastructure/docker/environments/dev/.env.dev"
	if data, err := os.ReadFile(devEnvPath); err == nil {
		lines := string(data)
		// Simple parsing to extract SECRET_KEY
		for _, line := range splitLines(lines) {
			if len(line) > 11 && line[:11] == "SECRET_KEY=" {
				key := line[11:]
				if key != "" && key != "<SECRET_KEY>" {
					return key
				}
			}
		}
	}

	fmt.Fprintf(os.Stderr, "Warning: SECRET_KEY not found, using placeholder. Set SECRET_KEY env var or provide as argument.\n")
	return "your-secret-key-here-change-in-production"
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i, ch := range []byte(s) {
		if ch == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

func printTokenInfo(tokenString, secretKey string) {
	// Parse token to show claims
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		return []byte(secretKey), nil
	})
	if err != nil {
		return
	}

	if claims, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
		_, _ = fmt.Fprintln(os.Stdout, "\n📋 JWT Token Info:")
		pretty, _ := json.MarshalIndent(claims, "  ", "  ")
		_, _ = fmt.Fprintf(os.Stdout, "  %s\n", string(pretty))

		if exp, ok := claims[claimskeys.Exp].(float64); ok {
			expTime := time.Unix(int64(exp), 0)
			_, _ = fmt.Fprintf(os.Stdout, "\n  Expires: %s\n", expTime.Format(time.RFC3339))
			_, _ = fmt.Fprintf(os.Stdout, "  Valid for: %s\n", time.Until(expTime).Round(time.Second))
		}
	}
}
