// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type CategoryCount struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

type ChatContext struct {
	RecentChats     []*ChatMessage `json:"recentChats"`
	TotalRecords    int32          `json:"totalRecords"`
	TotalCategories int32          `json:"totalCategories"`
	TotalTags       int32          `json:"totalTags"`
}

type ChatMessage struct {
	ID            string  `json:"id"`
	UserID        string  `json:"userId"`
	Message       string  `json:"message"`
	Response      string  `json:"response"`
	TokensUsed    int32   `json:"tokensUsed"`
	FunctionCalls *string `json:"functionCalls,omitempty"`
	CreatedAt     string  `json:"createdAt"`
	UpdatedAt     string  `json:"updatedAt"`
}

type CreateCategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type CreateRecordInput struct {
	TagID           string   `json:"tagId"`
	Description     *string  `json:"description,omitempty"`
	EventTime       *string  `json:"eventTime,omitempty"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

type CreateTagInput struct {
	Name        string  `json:"name"`
	CategoryID  string  `json:"categoryId"`
	Description *string `json:"description,omitempty"`
}

type DeleteCategoryInput struct {
	ID string `json:"id"`
}

type DeleteRecordInput struct {
	ID string `json:"id"`
}

type DeleteTagInput struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type Record struct {
	ID              string   `json:"id"`
	UserID          string   `json:"userId"`
	TagID           string   `json:"tagId"`
	Description     *string  `json:"description,omitempty"`
	EventTime       string   `json:"eventTime"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
	CreatedAt       string   `json:"createdAt"`
	UpdatedAt       string   `json:"updatedAt"`
}

type SearchFilters struct {
	Query       string   `json:"query"`
	CategoryIds []string `json:"categoryIds,omitempty"`
	TagIds      []string `json:"tagIds,omitempty"`
	StartDate   *string  `json:"startDate,omitempty"`
	EndDate     *string  `json:"endDate,omitempty"`
	Limit       *int32   `json:"limit,omitempty"`
	Offset      *int32   `json:"offset,omitempty"`
}

type Tag struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	CategoryID  string  `json:"categoryId"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type TagCount struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

type UpdateCategoryInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type UpdateRecordInput struct {
	ID              string   `json:"id"`
	Description     *string  `json:"description,omitempty"`
	TagID           *string  `json:"tagId,omitempty"`
	EventTime       *string  `json:"eventTime,omitempty"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

type UpdateTagInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	CategoryID  *string `json:"categoryId,omitempty"`
	Description *string `json:"description,omitempty"`
}

type UserStats struct {
	TotalRecords     int32          `json:"totalRecords"`
	TotalCategories  int32          `json:"totalCategories"`
	TotalTags        int32          `json:"totalTags"`
	RecordsThisWeek  int32          `json:"recordsThisWeek"`
	RecordsThisMonth int32          `json:"recordsThisMonth"`
	MostUsedCategory *CategoryCount `json:"mostUsedCategory,omitempty"`
	MostUsedTag      *TagCount      `json:"mostUsedTag,omitempty"`
}
