// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type CategoryCount struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

type ChatContext struct {
	RecentChats     []*ChatMessage `json:"recentChats"`
	TotalRecords    int32          `json:"totalRecords"`
	TotalCategories int32          `json:"totalCategories"`
	TotalTags       int32          `json:"totalTags"`
}

type ChatDataPack struct {
	Categories    []*Category `json:"categories"`
	Tags          []*Tag      `json:"tags"`
	RecentRecords []*Record   `json:"recentRecords"`
	UserStats     *UserStats  `json:"userStats,omitempty"`
}

type ChatMessage struct {
	ID            string  `json:"id"`
	UserID        string  `json:"userId"`
	Message       string  `json:"message"`
	Response      string  `json:"response"`
	TokensUsed    int32   `json:"tokensUsed"`
	FunctionCalls *string `json:"functionCalls,omitempty"`
	CreatedAt     string  `json:"createdAt"`
	UpdatedAt     string  `json:"updatedAt"`
}

type CreateCategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type CreateRecordInput struct {
	TagID           string   `json:"tagId"`
	Description     *string  `json:"description,omitempty"`
	EventTime       *string  `json:"eventTime,omitempty"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

type CreateTagInput struct {
	Name        string  `json:"name"`
	CategoryID  string  `json:"categoryId"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type DashboardGoal struct {
	GoalID       string  `json:"goalId"`
	Title        string  `json:"title"`
	MetricKey    string  `json:"metricKey"`
	CurrentValue float64 `json:"currentValue"`
	TargetValue  float64 `json:"targetValue"`
	ProgressPct  float64 `json:"progressPct"`
	Status       string  `json:"status"`
}

type DashboardMetric struct {
	MetricKey   string   `json:"metricKey"`
	Label       string   `json:"label"`
	Value       float64  `json:"value"`
	Unit        string   `json:"unit"`
	Target      *float64 `json:"target,omitempty"`
	ProgressPct float64  `json:"progressPct"`
	Status      string   `json:"status"`
}

type DashboardSnapshot struct {
	Date     string             `json:"date"`
	Timezone string             `json:"timezone"`
	Metrics  []*DashboardMetric `json:"metrics"`
	Goals    []*DashboardGoal   `json:"goals"`
}

type DeleteCategoryInput struct {
	ID string `json:"id"`
}

type DeleteGoalTemplateInput struct {
	ID string `json:"id"`
}

type DeleteRecordInput struct {
	ID string `json:"id"`
}

type DeleteTagInput struct {
	ID string `json:"id"`
}

type GoalTemplate struct {
	ID          string  `json:"id"`
	MetricKey   string  `json:"metricKey"`
	Title       string  `json:"title"`
	TargetValue float64 `json:"targetValue"`
	Comparison  string  `json:"comparison"`
	Period      string  `json:"period"`
	IsActive    bool    `json:"isActive"`
}

type MetricDefinition struct {
	ID          string   `json:"id"`
	MetricKey   string   `json:"metricKey"`
	DisplayName string   `json:"displayName"`
	CategoryID  *string  `json:"categoryId,omitempty"`
	TagID       string   `json:"tagId"`
	TagIds      []string `json:"tagIds"`
	ValueSource string   `json:"valueSource"`
	Aggregation string   `json:"aggregation"`
	Unit        string   `json:"unit"`
	GoalDefault *float64 `json:"goalDefault,omitempty"`
	IsActive    bool     `json:"isActive"`
}

type Mutation struct {
}

type Query struct {
}

type Record struct {
	ID              string   `json:"id"`
	UserID          string   `json:"userId"`
	TagID           string   `json:"tagId"`
	Description     *string  `json:"description,omitempty"`
	EventTime       string   `json:"eventTime"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
	CreatedAt       string   `json:"createdAt"`
	UpdatedAt       string   `json:"updatedAt"`
}

type RecordStats struct {
	TotalRecords         int32    `json:"totalRecords"`
	RecordsWithValue     int32    `json:"recordsWithValue"`
	TotalDurationSeconds int32    `json:"totalDurationSeconds"`
	SumValue             float64  `json:"sumValue"`
	AvgValue             float64  `json:"avgValue"`
	AvgDurationSeconds   float64  `json:"avgDurationSeconds"`
	MinValue             *float64 `json:"minValue,omitempty"`
	MaxValue             *float64 `json:"maxValue,omitempty"`
}

type RecordStatsFilters struct {
	Query       *string  `json:"query,omitempty"`
	CategoryIds []string `json:"categoryIds,omitempty"`
	TagIds      []string `json:"tagIds,omitempty"`
	StartDate   *string  `json:"startDate,omitempty"`
	EndDate     *string  `json:"endDate,omitempty"`
	Limit       *int32   `json:"limit,omitempty"`
}

type SearchFilters struct {
	Query       string   `json:"query"`
	CategoryIds []string `json:"categoryIds,omitempty"`
	TagIds      []string `json:"tagIds,omitempty"`
	StartDate   *string  `json:"startDate,omitempty"`
	EndDate     *string  `json:"endDate,omitempty"`
	Limit       *int32   `json:"limit,omitempty"`
	Offset      *int32   `json:"offset,omitempty"`
}

type Tag struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	CategoryID  string  `json:"categoryId"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type TagCount struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Count int32  `json:"count"`
}

type UpdateCategoryInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ColorHex    *string `json:"colorHex,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type UpdateRecordInput struct {
	ID              string   `json:"id"`
	Description     *string  `json:"description,omitempty"`
	TagID           *string  `json:"tagId,omitempty"`
	EventTime       *string  `json:"eventTime,omitempty"`
	RecordedAt      *string  `json:"recordedAt,omitempty"`
	DurationSeconds *int32   `json:"durationSeconds,omitempty"`
	Value           *float64 `json:"value,omitempty"`
	Source          *string  `json:"source,omitempty"`
	Timezone        *string  `json:"timezone,omitempty"`
	Status          *string  `json:"status,omitempty"`
}

type UpdateTagInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	CategoryID  *string `json:"categoryId,omitempty"`
	Description *string `json:"description,omitempty"`
	Icon        *string `json:"icon,omitempty"`
}

type UpsertGoalTemplateInput struct {
	ID          *string `json:"id,omitempty"`
	MetricKey   string  `json:"metricKey"`
	Title       string  `json:"title"`
	TargetValue float64 `json:"targetValue"`
	Comparison  *string `json:"comparison,omitempty"`
	Period      *string `json:"period,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type UpsertMetricDefinitionInput struct {
	ID          *string  `json:"id,omitempty"`
	MetricKey   string   `json:"metricKey"`
	DisplayName string   `json:"displayName"`
	CategoryID  *string  `json:"categoryId,omitempty"`
	TagID       string   `json:"tagId"`
	TagIds      []string `json:"tagIds,omitempty"`
	ValueSource *string  `json:"valueSource,omitempty"`
	Aggregation *string  `json:"aggregation,omitempty"`
	Unit        *string  `json:"unit,omitempty"`
	GoalDefault *float64 `json:"goalDefault,omitempty"`
	IsActive    *bool    `json:"isActive,omitempty"`
}

type UserStats struct {
	TotalRecords     int32          `json:"totalRecords"`
	TotalCategories  int32          `json:"totalCategories"`
	TotalTags        int32          `json:"totalTags"`
	RecordsThisWeek  int32          `json:"recordsThisWeek"`
	RecordsThisMonth int32          `json:"recordsThisMonth"`
	MostUsedCategory *CategoryCount `json:"mostUsedCategory,omitempty"`
	MostUsedTag      *TagCount      `json:"mostUsedTag,omitempty"`
}
