package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/lechitz/AionApi/adapters/primary/graph/model"
	"github.com/lechitz/AionApi/internal/core/domain"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		return nil, fmt.Errorf("userID not found in context")
	}

	category := domain.Category{
		UserID:      userID,
		Name:        input.Name,
		Description: *input.Description,
		Color:       *input.ColorHex,
		Icon:        *input.Icon,
	}

	categoryDB, err := r.Resolver.CategoryService.CreateCategory(ctx, category)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  fmt.Sprintf("%d", categoryDB.ID),
		UserID:      fmt.Sprintf("%d", categoryDB.UserID),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(_ context.Context, _ model.NewTag) (*model.Tags, error) {
	panic(fmt.Errorf("not implemented: CreateTag - createTag"))
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	categoryDB, err := r.Resolver.CategoryService.GetAllCategories(ctx)
	if err != nil {
		return nil, errors.New("failed to fetch categories")
	}

	categories := make([]*model.Category, len(categoryDB))
	for i, category := range categoryDB {
		categories[i] = &model.Category{
			CategoryID:  fmt.Sprintf("%d", category.ID),
			UserID:      fmt.Sprintf("%d", category.UserID),
			Name:        category.Name,
			Description: &category.Description,
			ColorHex:    &category.Color,
			Icon:        &category.Icon,
		}
	}

	return categories, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, categoryID string) (*model.Category, error) {
	categoryIDUint, err := strconv.ParseUint(categoryID, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID format")
	}

	category := domain.Category{
		ID: categoryIDUint,
	}

	categoryDB, err := r.Resolver.CategoryService.GetCategoryByID(ctx, category.ID)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  fmt.Sprintf("%d", categoryDB.ID),
		UserID:      fmt.Sprintf("%d", categoryDB.UserID),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(_ context.Context) ([]*model.Tags, error) {
	panic(fmt.Errorf("not implemented: Tags - tags"))
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(_ context.Context, _ *string) (*model.Tags, error) {
	panic(fmt.Errorf("not implemented: Tag - tag"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
