// Package graph implements the GraphQL resolvers for the API.
package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating, and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.72

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/lechitz/AionApi/adapters/primary/graph/model"
	"github.com/lechitz/AionApi/internal/core/domain"
)

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, category model.DtoCreateCategory) (*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		return nil, errors.New("userID not found in context")
	}

	createCategory := domain.Category{
		UserID:      userID,
		Name:        category.Name,
		Description: *category.Description,
		Color:       *category.ColorHex,
		Icon:        *category.Icon,
	}

	categoryDB, err := r.CategoryService.CreateCategory(ctx, createCategory)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(userID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(_ context.Context, _ model.NewTag) (*model.Tags, error) {
	return nil, errors.New("not implemented")
}

// UpdateCategory is the resolver for the UpdateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, category model.DtoUpdateCategory) (*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		return nil, errors.New("userID not found in context")
	}

	categoryIDUint, err := strconv.ParseUint(category.CategoryID, 10, 64)
	if err != nil {
		return nil, errors.New("invalid category ID format")
	}

	updateCategory := domain.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	if category.Name != nil {
		updateCategory.Name = *category.Name
	}
	if category.Description != nil {
		updateCategory.Description = *category.Description
	}
	if category.ColorHex != nil {
		updateCategory.Color = *category.ColorHex
	}
	if category.Icon != nil {
		updateCategory.Icon = *category.Icon
	}

	categoryDB, err := r.CategoryService.UpdateCategory(ctx, updateCategory)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      fmt.Sprintf("%d", categoryDB.UserID),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// SoftDeleteCategory is the resolver for the SoftDeleteCategory field.
func (r *mutationResolver) SoftDeleteCategory(ctx context.Context, category model.DtoDeleteCategory) (bool, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		return false, errors.New("userID not found in context")
	}

	categoryIDUint, err := strconv.ParseUint(category.CategoryID, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid category ID format: %w", err)
	}

	categoryDomain := domain.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	if err := r.CategoryService.SoftDeleteCategory(ctx, categoryDomain); err != nil {
		return false, err
	}

	return true, nil
}

// AllCategories is the resolver for the AllCategories field.
func (r *queryResolver) AllCategories(ctx context.Context) ([]*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		r.Logger.Errorw("User ID not found in context", "error", "userID not found in context")
		return nil, errors.New("userID not found in context")
	}

	categoryDB, err := r.CategoryService.GetAllCategories(ctx, userID)
	if err != nil {
		return nil, errors.New("failed to fetch categories")
	}

	categories := make([]*model.Category, len(categoryDB))
	for i, category := range categoryDB {
		categories[i] = &model.Category{
			CategoryID:  strconv.FormatUint(category.ID, 10),
			UserID:      strconv.FormatUint(userID, 10),
			Name:        category.Name,
			Description: &category.Description,
			ColorHex:    &category.Color,
			Icon:        &category.Icon,
		}
	}

	return categories, nil
}

// GetCategoryByID is the resolver for the GetCategoryByID field.
func (r *queryResolver) GetCategoryByID(ctx context.Context, categoryRequest model.DtoGetCategoryByID) (*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		r.Logger.Errorw("User ID not found in context", "error", "userID not found in context")
		return nil, errors.New("userID not found in context")
	}

	categoryIDUint, err := strconv.ParseUint(categoryRequest.CategoryID, 10, 64)
	if err != nil {
		return nil, errors.New("invalid category ID format")
	}

	category := domain.Category{
		ID:     categoryIDUint,
		UserID: userID,
	}

	categoryDB, err := r.CategoryService.GetCategoryByID(ctx, category)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  strconv.FormatUint(categoryDB.ID, 10),
		UserID:      strconv.FormatUint(categoryDB.UserID, 10),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// GetCategoryByName is the resolver for the GetCategoryByName field.
func (r *queryResolver) GetCategoryByName(ctx context.Context, categoryRequest model.DtoGetCategoryByName) (*model.Category, error) {
	userID, ok := ctx.Value("user_id").(uint64)
	if !ok {
		r.Logger.Errorw("User ID not found in context", "error", "userID not found in context")
		return nil, errors.New("userID not found in context")
	}

	category := domain.Category{
		UserID: userID,
		Name:   categoryRequest.Name,
	}

	categoryDB, err := r.CategoryService.GetCategoryByName(ctx, category)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		CategoryID:  fmt.Sprintf("%d", categoryDB.ID),
		UserID:      fmt.Sprintf("%d", categoryDB.UserID),
		Name:        categoryDB.Name,
		Description: &categoryDB.Description,
		ColorHex:    &categoryDB.Color,
		Icon:        &categoryDB.Icon,
	}, nil
}

// GetAllTags is the resolver for the GetAllTags field.
func (r *queryResolver) GetAllTags(_ context.Context) ([]*model.Tags, error) {
	panic(fmt.Errorf("not implemented: GetAllTags - GetAllTags"))
	return nil, nil
}

// GetTagByID is the resolver for the GetTagByID field.
func (r *queryResolver) GetTagByID(_ context.Context, _ string) (*model.Tags, error) {
	panic(fmt.Errorf("not implemented: GetTagByID - GetTagByID"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// mutationResolver serves as the GraphQL resolver implementation for mutation-related operations.
// It embeds the Resolver to access shared services and utilities.
type mutationResolver struct{ *Resolver }

// queryResolver is a GraphQL type implementing the QueryResolver interface for handling query operations.
// It embeds Resolver to access services and logging utilities.
type queryResolver struct{ *Resolver }
