name: "DevOps Task"
description: "Describe a task related to DevOps or infrastructure."
title: "[DEVOPS] Brief description of the DevOps task"
labels: ["devops"]
body:
  - type: markdown
    attributes:
      value: |
        ## General Information
        - **Priority:** *(Low / Medium / High / Critical)*
        - **Status:** *(To Do / In Progress / Review / Done)*
        - **Creation Date:** *(YYYY-MM-DD)*

        ---

  - type: textarea
    id: task_scope
    attributes:
      label: "Scope of Task"
      description: "Explain the context and details of the DevOps task, including the systems or infrastructure involved."
      placeholder: "Describe the scope of the task here."

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      options:
        - label: "Criterion 1"
        - label: "Criterion 2"
        - label: "Criterion 3"

  - type: markdown
    attributes:
      value: |
        ## Execution Plan
  - type: textarea
    id: execution_plan
    attributes:
      label: "Execution Plan"
      description: "Explain the steps required to complete the task, including tools, configurations, and deployment strategies."
      placeholder: "Detail the execution plan for the DevOps task."

  - type: markdown
    attributes:
      value: |
        ## Impacts
  - type: textarea
    id: impacts
    attributes:
      label: "Impacts"
      description: "List positive impacts (improved reliability, scalability) and negative impacts (risks or downtime)."
      placeholder: "Detail the impacts here."
