name: "Documentation Task"
description: "Describe a task related to documentation."
title: "[DOCS] Brief description of the documentation task"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## General Information
        - **Priority:** *(Low / Medium / High / Critical)*
        - **Status:** *(To Do / In Progress / Review / Done)*
        - **Creation Date:** *(YYYY-MM-DD)*

        ---

  - type: textarea
    id: doc_scope
    attributes:
      label: "Scope of Documentation"
      description: "Explain what needs to be documented or updated, including the context and relevance."
      placeholder: "Describe the scope of documentation here."

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      options:
        - label: "Criterion 1"
        - label: "Criterion 2"
        - label: "Criterion 3"

  - type: markdown
    attributes:
      value: |
        ## Execution Plan
  - type: textarea
    id: execution_plan
    attributes:
      label: "Execution Plan"
      description: "Explain the approach or steps required to complete the documentation task. Include specific formats, sections, or tools to be used."
      placeholder: "Detail the execution plan for documentation."

  - type: markdown
    attributes:
      value: |
        ## Impacts
  - type: textarea
    id: impacts
    attributes:
      label: "Impacts"
      description: "List positive impacts (clarifications or enhancements) and negative impacts (potential misunderstandings if not completed)."
      placeholder: "Detail the impacts here."
