name: "Refactor Task"
description: "Plan and track a code refactoring task."
title: "[REFACTOR] Brief description of the refactor"
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ## General Information
        - **Priority:** *(Low / Medium / High / Critical)*
        - **Status:** *(To Do / In Progress / Review / Done)*
        - **Creation Date:** *(YYYY-MM-DD)*

        ---

  - type: textarea
    id: refactor_details
    attributes:
      label: "Refactor Details"
      description: "Describe the part of the codebase to be refactored and why it is necessary."
      placeholder: "Explain the scope and reason for the refactor."

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
  - type: checkboxes
    id: acceptance_criteria
    attributes:
      label: "Acceptance Criteria"
      options:
        - label: "Criterion 1"
        - label: "Criterion 2"
        - label: "Criterion 3"

  - type: markdown
    attributes:
      value: |
        ## Execution Plan
  - type: textarea
    id: execution_plan
    attributes:
      label: "Execution Plan"
      description: "Explain the approach or technical solution to be implemented. Include steps, strategies, and changes expected in the codebase."
      placeholder: "Detail the execution plan."

  - type: markdown
    attributes:
      value: |
        ## Impacts
  - type: textarea
    id: impacts
    attributes:
      label: "Impacts"
      description: "List positive impacts (improvements or benefits) and negative impacts (possible risks or challenges)."
      placeholder: "Detail the impacts here."
