package graphql

import "context"

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating, and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.74

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// Empty is a placeholder resolver to avoid gqlgen errors when no other resolvers are defined.
func (m *mutationResolver) Empty(_ context.Context) (*bool, error) { return nil, nil }

// Empty is a placeholder resolver to avoid gqlgen errors when no other resolvers are defined.
func (q *queryResolver) Empty(_ context.Context) (*bool, error) { return nil, nil }
