{
 "title": "AionAPI - HTTP Request Count",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AionAPI - HTTP POST",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  http_server_request_duration_seconds_count{http_request_method=\"POST\"}\n)",
     "legendFormat": "{{http_request_method}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "AionAPI - HTTP GET",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  http_server_request_duration_seconds_count{http_request_method=\"GET\"}\n)",
     "legendFormat": "{{http_request_method}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "AionAPI - HTTP PUT",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  http_server_request_duration_seconds_count{http_request_method=\"PUT\"}\n)",
     "legendFormat": "{{http_request_method}} {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "AionAPI - HTTP DELETE",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_response_status_code) (\n  http_server_request_duration_seconds_count{http_request_method=\"DELETE\"}\n)",
     "legendFormat": "{{http_request_method}} {{http_response_status_code}}"
    }
   ]
  }
 ]
}