[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Tag               docker.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /fluent-bit/state/flb.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[FILTER]
    Name           docker
    Match          docker.*
    Merge_Log      On
    Merge_Log_Key  log
    Keep_Log       Off
    Labels         On
    Env            On

[FILTER]
    Name           modify
    Match          docker.*
    Add            env ${APP_ENV}

[OUTPUT]
    Name           loki
    Match          docker.*
    Host           loki
    Port           3100
    Labels         job=fluentbit,env=${APP_ENV}
    LabelKeys      container_name,container_id,stream,level
    LineFormat     json
