CREATE TABLE IF NOT EXISTS aion_api.users
(
    user_id    SERIAL PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(255) NOT NULL UNIQUE,
    roles      VARCHAR(20) NOT NULL DEFAULT 'user',
    locale     VARCHAR(16) DEFAULT NULL,
    timezone   VARCHAR(64) DEFAULT NULL,
    location   VARCHAR(255) DEFAULT NULL,
    bio        TEXT DEFAULT NULL,
    avatar_url TEXT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL
);
