# ============================================================
#                         SWAG DOCS
# Purpose:
# - docs.gen:         generate/refresh committed swagger artifacts
# - docs.validate:    validate artifacts are up-to-date (no workspace changes)
# - docs.check-dirty: CI-only guard using git diff on tracked files
# ============================================================

SWAG_VERSION ?= v1.16.6
SWAG_BIN     = $(shell [ -x "$(CURDIR)/.cache/bin/swag" ] && echo "$(CURDIR)/.cache/bin/swag" || command -v swag || echo "$$(go env GOPATH)/bin/swag")
SWAG_OUT     ?= contracts/openapi
SWAG_DIRS    ?= ./cmd/api,./internal/admin/adapter/primary/http/handler,./internal/auth/adapter/primary/http/handler,./internal/chat/adapter/primary/http/handler,./internal/user/adapter/primary/http/handler
SWAG_MAIN    ?= swagger.go
SWAG_PKG     ?= docs
GO_CACHE     ?= $(CURDIR)/.cache/go-build

PERL_BIN     ?= $(shell command -v perl)

.PHONY: tools.s swag docs.gen docs.clean docs.check-dirty docs.validate

tools.s:
	@echo ">> ensuring tools"

swag: tools.s
	@echo ">> ensuring swag $(SWAG_VERSION)"
	@mkdir -p "$(GO_CACHE)"
	@if [ -x "$(SWAG_BIN)" ]; then \
		INSTALLED_VERSION=$$(go version -m "$(SWAG_BIN)" 2>/dev/null | awk '$$1=="mod" && $$2=="github.com/swaggo/swag"{print $$3}' | head -n1); \
		if [ -z "$$INSTALLED_VERSION" ]; then \
			INSTALLED_VERSION=$$($(SWAG_BIN) --version | awk '{print $$3}'); \
		fi; \
		echo ">> swag already present at $(SWAG_BIN) (version: $$INSTALLED_VERSION)"; \
		if [ "$$INSTALLED_VERSION" != "$(SWAG_VERSION)" ]; then \
			echo ">> installing swag $(SWAG_VERSION) to .cache/bin"; \
			GOCACHE=$(GO_CACHE) GOBIN="$(CURDIR)/.cache/bin" go install github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION) || { \
				echo "⚠️  failed to install swag $(SWAG_VERSION); using existing $$INSTALLED_VERSION at $(SWAG_BIN)"; \
			}; \
		fi; \
	else \
		echo ">> installing swag $(SWAG_VERSION)"; \
		GOCACHE=$(GO_CACHE) GOBIN="$(CURDIR)/.cache/bin" go install github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION) || { \
			echo "❌ failed to install swag (likely offline). Install manually if needed: go install github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION)"; \
			exit 1; \
		}; \
	fi

docs.gen: swag
	@echo ">> generating swagger docs"
	@"$(SWAG_BIN)" init \
		-g "$(SWAG_MAIN)" \
		-o "$(SWAG_OUT)" \
		--packageName "$(SWAG_PKG)" \
		--parseDependency \
		--parseInternal \
		-d "$(SWAG_DIRS)"

	@echo ">> patching generated docs.go for lint (godot + nolintlint, with reasons; idempotent)"
	@[ -n "$(PERL_BIN)" ] || (echo "Perl not found. Please install Perl to patch generated docs."; exit 1)
	@[ -f "$(SWAG_OUT)/docs.go" ] || (echo "$(SWAG_OUT)/docs.go not found"; exit 1)
	@$(PERL_BIN) -0777 -i -pe 's{^// SwaggerInfo holds exported Swagger Info so clients can modify it(?!\.)$$}{$$&.}m' "$(SWAG_OUT)/docs.go"
	@$(PERL_BIN) -0777 -i -pe 's{^(var SwaggerInfo = \&swag\.Spec\{)(?!.*gochecknoglobals)}{$$1 //nolint:gochecknoglobals // generated by swag: global spec is required for registration}m' "$(SWAG_OUT)/docs.go"
	@$(PERL_BIN) -0777 -i -pe 's{^(func init\(\) \{)(?!.*gochecknoinits)}{$$1 //nolint:gochecknoinits // generated by swag: init is required to register spec}m' "$(SWAG_OUT)/docs.go"

docs.clean:
	@echo ">> cleaning swagger docs"
	@rm -rf "$(SWAG_OUT)"

# CI-only guard that fails if tracked swagger artifacts changed vs HEAD.
docs.check-dirty:
	@git diff --quiet -- "$(SWAG_OUT)" || (echo "Swagger docs out-of-date. Run 'make docs.gen'."; exit 1)

# Local guard that does NOT modify the workspace:
# 1) generate to a temp dir OUTSIDE of compare tree ($TMP_DIR/out)
# 2) apply same lint patches
# 3) diff with committed artifacts and print differences if any
docs.validate: swag
	@echo ">> validating swagger docs are up-to-date"
	"$(SWAG_BIN)" init \
		-g "$(SWAG_MAIN)" \
		-o "$(SWAG_OUT)" \
		--packageName "$(SWAG_PKG)" \
		--parseDependency \
		--parseInternal \
		-d "$(SWAG_DIRS)"
	@echo ">> patching generated docs.go for lint (godot + nolintlint, with reasons; idempotent)"
	@[ -n "$(PERL_BIN)" ] || (echo "Perl not found. Please install Perl to patch generated docs."; exit 1)
	@[ -f "$(SWAG_OUT)/docs.go" ] || (echo "$(SWAG_OUT)/docs.go not found"; exit 1)
	@$(PERL_BIN) -0777 -i -pe 's{^// SwaggerInfo holds exported Swagger Info so clients can modify it(?!\.)$$}{$$&.}m' "$(SWAG_OUT)/docs.go"
	@$(PERL_BIN) -0777 -i -pe 's{^(var SwaggerInfo = \&swag\.Spec\{)(?!.*gochecknoglobals)}{$$1 //nolint:gochecknoglobals // generated by swag: global spec is required for registration}m' "$(SWAG_OUT)/docs.go"
	@$(PERL_BIN) -0777 -i -pe 's{^(func init\(\) \{)(?!.*gochecknoinits)}{$$1 //nolint:gochecknoinits // generated by swag: init is required to register spec}m' "$(SWAG_OUT)/docs.go"
	@echo ">> swagger docs generated successfully!"
