# .github/workflows/lint.yml
# ---------------------------------------------------------------------
# Lint Workflow for AionAPI (Go)
# Purpose: Perform static code analysis using golangci-lint and govet.
#          Uses reviewdog to add inline comments directly to Pull Requests.
# Trigger: Runs on every push to PRs targeting the 'main' branch.
# ---------------------------------------------------------------------

name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Clean Go mod cache
        run: go clean -modcache

      - name: Fix cache permissions
        run: |
          chmod -R 0755 ~/.cache/go-build ~/go/pkg/mod

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Cache golangci-lint cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golangci-lint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangci-lint-

      - name: Install golangci-lint
        run: curl -sSfL https://... | sh -s -- -b $(go env GOPATH)/bin v1.56.2

      - name: Run golangci-lint via reviewdog
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--config=.golangci.yml ./..."
          level: warning
          reporter: github-pr-review
          fail_level: error

      - name: Run go vet
        run: go vet ./...
